<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Aptech._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
          <div id="content">
        <div class="outer">
          <div class="inner bg-light lter">
            <div class="col-lg-12">
              <h1 id="bootstrap-admin-template-build-status-https-travis-ci-org-onokumus-bootstrap-admin-template-png-https-travis-ci-org-onokumus-bootstrap-admin-template-dependency-status-https-david-dm-org-onokumus-bootstrap-admin-template-svg-theme-shields-io-https-david-dm-org-onokumus-bootstrap-admin-template-devdependency-status-https-david-dm-org-onokumus-bootstrap-admin-template-dev-status-svg-theme-shields-io-https-david-dm-org-onokumus-bootstrap-admin-template-info-devdependencies-">Bootstrap-Admin-Template
               
              </h1>
              <blockquote>
                <p>Free Admin Template Based On Twitter Bootstrap 3.x</p>
              </blockquote>
              <h2 id="release-history">Release History</h2>
              <p><strong>DATE</strong>   <strong>VERSION</strong>   <strong>CHANGES</strong>  
              </p>
              <ul>
                <li>2014-07-18 v2.2.6.1 added some layouts sample</li>
                <li>2014-07-07 v2.2.6 Bootstrap 3.2.0</li>
                <li>2014-06-04 v2.2.5 Fixed side panel(s) code Deprecated main.js Added core.js &amp; app.js</li>
                <li>2014-04-23 v2.2.4 RTL version added Remove CLEditor Added CKEditor</li>
                <li>2014-04-13 v2.2.3 rewrite all code</li>
                <li>2014-04-10 v2.2.2 remove <code>alterne.html</code>,right panel available</li>
                <li>2014-04-07 v2.2.1 all dependency require bower &amp; npm</li>
                <li>2014-02-28 v2.2.0 rewrite menu, layout, etc</li>
                <li>2014-02-16 v2.1.4 update bootsrap 3.1.1 &amp;&amp; add screenfull.js &amp;&amp; fixed</li>
                <li>2014-01-19 v2.1.3 add suitcss &#39;s flex-embed component</li>
                <li>2013-11-30 v2.1.2 create menu plugin, rewrite <code>menu.less</code> 
                </li>
                <li>2013-10-28 v2.1.1.2 add bower</li>
                <li>2013-10-28 v2.1.1.1 remove bootsrap, font awesome, gmaps submodule.</li>
                <li>2013-10-23 v2.1.1 Added <code>bgimage.html</code> Added <code>bgcolor.html</code> pages.</li>
                <li>2013-10-22 v2.1 I don&#39;t remember. Whatever I did.</li>
                <li>2013-02-14 v1.0 First Commit.</li>
              </ul>
              <h3 id="author">Author</h3>
              <ul>
                <li>onokumus</li>
              </ul>
              <h3 id="license">License</h3>
              <p>Copyright (c) 2014 onokumus, contributors.</p>
              <p><em>This file was generated by <a href="https://github.com/assemble/verb-cli">verb-cli</a>  on July 18, 2014.</em> 
              </p>
            </div>
          </div><!-- /.inner -->
        </div><!-- /.outer -->
      </div><!-- /#content -->

</asp:Content>
